name: library 
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '40 7  * * *'

jobs:
  run-python-script:
    runs-on: ubuntu20.04 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'
      - run: pip install -t . -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - run: python libs/reserve.py
      
